### ISSUE TITLE
Chunks not marked correctly

### ISSUE THREAD

**Issue by engin33rguy** [senseiwells/ChunkDebug#4]
**Describe the bug**
Chunks around the player aren't being marked correctly in the ChunkDebug window. I first noticed this in 1.18.X and now can give you details from 1.19.2. (I know it's not super useful just saying "I saw it in 18" but unless you think it'll be really helpful to get 18 information in addition to what I have from 19 you just get anecdotal evidence)

**General Info**
Mod Version: Carpet 1.4.83, EssentialClient 1.3.0, ChunkDebug 1.0.4 
Minecraft Version: 1.19.2 Server
List of other mods: advancementinfo, amecs, antighost, betterdarkmode, betterF3, borderlessmining, cleardespawn, clientcommands, cmdkeybind, continuity, fabricapi, carpet, indium, iris, itemscroller, lazydfu, litematica, malilib, minihud, modmenu, sodium, starlight, tweakermore, tweakeroo, xaerosminimap, xaerosworldmap. (All latest versions)

**To Reproduce**

1. Install latest carpet, essentialclient, chunkdebug
2. Create a world
3. Move away from spawn so that the player-loaded area doesn't overlap with spawn chunks.
4. See that the border chunks are correct, but every other player-loaded chunk is marked as lazy. https://i.imgur.com/sf9EnKw.png

**Expected behavior**
Player-loaded chunks should be marked as green, not yellow (lazy). This worked in 1.17 but I don't think it worked in 18 and definitely isn't working in 19.

**Crash Report / Lastest Log**
Upload your crash report or latest log to help us figure out what's going on.

**Screenshots / Videos**
https://i.imgur.com/sf9EnKw.png

**Additional info**
I'm engin33rguy#2407 on discord if it's easier to communicate there, or on the Mechanists discord too. (That's where we first noticed it, but now it's showing up in my SMP too.)

**Comment by senseiwells** [comment]
Try [this version](https://github.com/senseiwells/ChunkDebug/actions/runs/3032568004)
You'll need to download the artifacts and extract them from here.

I also changed some stuff in EC, you can use older versions just player loaded chunks will force chunks to be green thus it looks like the lazy chunks are entity ticking, find that [here](https://github.com/senseiwells/EssentialClient/actions/runs/3032570157)

**Comment by engin33rguy** [comment]
Thanks for this- I won't be able to update the server until later this afternoon but I wanted to say I appreciate the quick response. I'll let you know what happens when we upgrade later tonight.

**Comment by engin33rguy** [comment]
Server failed to launch, here's the log:

`[19:02:50] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
[19:02:50] [main/WARN]: Mod resolution failed
[19:02:50] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED chunkdebug 1.0.5 {depends minecraft @ [1.16.x]}, ROOT_FORCELOAD_SINGLE chunkdebug 1.0.5]
[19:02:50] [main/INFO]: Reason: [HARD_DEP chunkdebug 1.0.5 {depends minecraft @ [1.16.x]}]
[19:02:50] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, sodium, fabric-renderer-registries-v1, fabric-textures-v0, fabric-models-v0, fabric-client-tags-api-v1, fabric-screen-api-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-key-binding-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
[19:02:50] [main/INFO]: Fix: add [], remove [], replace [[chunkdebug 1.0.5] -> add:chunkdebug 1 ([(-∞,∞)])]
[19:02:50] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
     - Replace mod 'Chunk Debug' (chunkdebug) 1.0.5 with any version that is compatible with:
         - minecraft 1.19.2
Unmet dependency listing:
     - Mod 'Chunk Debug' (chunkdebug) 1.0.5 requires any 1.16.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
    at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.9.jar:?]
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.9.jar:?]
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.9.jar:?]
    at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
    at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
`

**Comment by senseiwells** [comment]
Oops! Should be fixed now, try the new build https://github.com/senseiwells/ChunkDebug/actions/runs/3033687004

**Comment by engin33rguy** [comment]
Works perfectly now as far as I can tell, thanks a lot!
